### ISSUE TITLE
AA4 script converter doesn't work.

### ISSUE THREAD

**Issue by TwistX32** [Aclios/AJT-Tools#3]
![image](https://github.com/user-attachments/assets/2632de01-55f5-4388-9d57-409b81770295)

**Comment by Aclios** [comment]
Hello, I am not sure what you are trying to do.

Both python files (aa4scriptconverter.py and aa56scriptconverter.py) only contains the functions to convert the scripts, so running them directly won't do anything. They are also using stuff from other files, that's why you have errors.

If you want to make it work, you need to either run the main.py file with the right arguments, or use the bat files that are included with the project. To export the files, you can just double click on the "EXTRACT.bat" of the right platform, after filling the path_init.txt file with the right data (everything is detailed in the README).

If you are only interested in extracting the text, you can just modify the bat file and remove the -png ; -sound arguments.
